name: container_tab_indicator
description: Build your own Tab indicator using familiar Container-like properties.
version: 0.2.0
homepage: https://github.com/slovnicki/container_tab_indicator
repository: https://github.com/slovnicki/container_tab_indicator

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true